//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Artnman.Commerce.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CommerceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CommerceEntities object using the connection string found in the 'CommerceEntities' section of the application configuration file.
        /// </summary>
        public CommerceEntities() : base("name=CommerceEntities", "CommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CommerceEntities object.
        /// </summary>
        public CommerceEntities(string connectionString) : base(connectionString, "CommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CommerceEntities object.
        /// </summary>
        public CommerceEntities(EntityConnection connection) : base(connection, "CommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cart> Cart
        {
            get
            {
                if ((_Cart == null))
                {
                    _Cart = base.CreateObjectSet<Cart>("Cart");
                }
                return _Cart;
            }
        }
        private ObjectSet<Cart> _Cart;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customer
        {
            get
            {
                if ((_Customer == null))
                {
                    _Customer = base.CreateObjectSet<Customer>("Customer");
                }
                return _Customer;
            }
        }
        private ObjectSet<Customer> _Customer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Order
        {
            get
            {
                if ((_Order == null))
                {
                    _Order = base.CreateObjectSet<Order>("Order");
                }
                return _Order;
            }
        }
        private ObjectSet<Order> _Order;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderDetail> OrderDetail
        {
            get
            {
                if ((_OrderDetail == null))
                {
                    _OrderDetail = base.CreateObjectSet<OrderDetail>("OrderDetail");
                }
                return _OrderDetail;
            }
        }
        private ObjectSet<OrderDetail> _OrderDetail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Product
        {
            get
            {
                if ((_Product == null))
                {
                    _Product = base.CreateObjectSet<Product>("Product");
                }
                return _Product;
            }
        }
        private ObjectSet<Product> _Product;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductCategory> ProductCategory
        {
            get
            {
                if ((_ProductCategory == null))
                {
                    _ProductCategory = base.CreateObjectSet<ProductCategory>("ProductCategory");
                }
                return _ProductCategory;
            }
        }
        private ObjectSet<ProductCategory> _ProductCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductImage> ProductImage
        {
            get
            {
                if ((_ProductImage == null))
                {
                    _ProductImage = base.CreateObjectSet<ProductImage>("ProductImage");
                }
                return _ProductImage;
            }
        }
        private ObjectSet<ProductImage> _ProductImage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductInfo> ProductInfo
        {
            get
            {
                if ((_ProductInfo == null))
                {
                    _ProductInfo = base.CreateObjectSet<ProductInfo>("ProductInfo");
                }
                return _ProductInfo;
            }
        }
        private ObjectSet<ProductInfo> _ProductInfo;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cart EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCart(Cart cart)
        {
            base.AddObject("Cart", cart);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomer(Customer customer)
        {
            base.AddObject("Customer", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Order EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrder(Order order)
        {
            base.AddObject("Order", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderDetail(OrderDetail orderDetail)
        {
            base.AddObject("OrderDetail", orderDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductCategory(ProductCategory productCategory)
        {
            base.AddObject("ProductCategory", productCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductImage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductImage(ProductImage productImage)
        {
            base.AddObject("ProductImage", productImage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductInfo(ProductInfo productInfo)
        {
            base.AddObject("ProductInfo", productInfo);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="languageId">No Metadata Documentation available.</param>
        /// <param name="pageSize">No Metadata Documentation available.</param>
        /// <param name="pageNumber">No Metadata Documentation available.</param>
        /// <param name="productCategoryId">No Metadata Documentation available.</param>
        public ObjectResult<ProductInfo> ProductInfo_GetByProductCategoryId_Child_Paging(global::System.String languageId, Nullable<global::System.Int32> pageSize, Nullable<global::System.Int32> pageNumber, Nullable<global::System.Guid> productCategoryId)
        {
            ObjectParameter languageIdParameter;
            if (languageId != null)
            {
                languageIdParameter = new ObjectParameter("LanguageId", languageId);
            }
            else
            {
                languageIdParameter = new ObjectParameter("LanguageId", typeof(global::System.String));
            }
    
            ObjectParameter pageSizeParameter;
            if (pageSize.HasValue)
            {
                pageSizeParameter = new ObjectParameter("PageSize", pageSize);
            }
            else
            {
                pageSizeParameter = new ObjectParameter("PageSize", typeof(global::System.Int32));
            }
    
            ObjectParameter pageNumberParameter;
            if (pageNumber.HasValue)
            {
                pageNumberParameter = new ObjectParameter("PageNumber", pageNumber);
            }
            else
            {
                pageNumberParameter = new ObjectParameter("PageNumber", typeof(global::System.Int32));
            }
    
            ObjectParameter productCategoryIdParameter;
            if (productCategoryId.HasValue)
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", productCategoryId);
            }
            else
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<ProductInfo>("ProductInfo_GetByProductCategoryId_Child_Paging", languageIdParameter, pageSizeParameter, pageNumberParameter, productCategoryIdParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="languageId">No Metadata Documentation available.</param>
        /// <param name="pageSize">No Metadata Documentation available.</param>
        /// <param name="pageNumber">No Metadata Documentation available.</param>
        /// <param name="productCategoryId">No Metadata Documentation available.</param>
        public ObjectResult<ProductInfo> ProductInfo_GetByProductCategoryId_Child_Paging(global::System.String languageId, Nullable<global::System.Int32> pageSize, Nullable<global::System.Int32> pageNumber, Nullable<global::System.Guid> productCategoryId, MergeOption mergeOption)
        {
            ObjectParameter languageIdParameter;
            if (languageId != null)
            {
                languageIdParameter = new ObjectParameter("LanguageId", languageId);
            }
            else
            {
                languageIdParameter = new ObjectParameter("LanguageId", typeof(global::System.String));
            }
    
            ObjectParameter pageSizeParameter;
            if (pageSize.HasValue)
            {
                pageSizeParameter = new ObjectParameter("PageSize", pageSize);
            }
            else
            {
                pageSizeParameter = new ObjectParameter("PageSize", typeof(global::System.Int32));
            }
    
            ObjectParameter pageNumberParameter;
            if (pageNumber.HasValue)
            {
                pageNumberParameter = new ObjectParameter("PageNumber", pageNumber);
            }
            else
            {
                pageNumberParameter = new ObjectParameter("PageNumber", typeof(global::System.Int32));
            }
    
            ObjectParameter productCategoryIdParameter;
            if (productCategoryId.HasValue)
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", productCategoryId);
            }
            else
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<ProductInfo>("ProductInfo_GetByProductCategoryId_Child_Paging", mergeOption, languageIdParameter, pageSizeParameter, pageNumberParameter, productCategoryIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="languageId">No Metadata Documentation available.</param>
        /// <param name="pageSize">No Metadata Documentation available.</param>
        /// <param name="pageNumber">No Metadata Documentation available.</param>
        /// <param name="productCategoryId">No Metadata Documentation available.</param>
        public ObjectResult<ProductInfo> ProductInfo_GetByProductCategoryId_Child_Paging_Visible(global::System.String languageId, Nullable<global::System.Int32> pageSize, Nullable<global::System.Int32> pageNumber, Nullable<global::System.Guid> productCategoryId)
        {
            ObjectParameter languageIdParameter;
            if (languageId != null)
            {
                languageIdParameter = new ObjectParameter("LanguageId", languageId);
            }
            else
            {
                languageIdParameter = new ObjectParameter("LanguageId", typeof(global::System.String));
            }
    
            ObjectParameter pageSizeParameter;
            if (pageSize.HasValue)
            {
                pageSizeParameter = new ObjectParameter("PageSize", pageSize);
            }
            else
            {
                pageSizeParameter = new ObjectParameter("PageSize", typeof(global::System.Int32));
            }
    
            ObjectParameter pageNumberParameter;
            if (pageNumber.HasValue)
            {
                pageNumberParameter = new ObjectParameter("PageNumber", pageNumber);
            }
            else
            {
                pageNumberParameter = new ObjectParameter("PageNumber", typeof(global::System.Int32));
            }
    
            ObjectParameter productCategoryIdParameter;
            if (productCategoryId.HasValue)
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", productCategoryId);
            }
            else
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<ProductInfo>("ProductInfo_GetByProductCategoryId_Child_Paging_Visible", languageIdParameter, pageSizeParameter, pageNumberParameter, productCategoryIdParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="languageId">No Metadata Documentation available.</param>
        /// <param name="pageSize">No Metadata Documentation available.</param>
        /// <param name="pageNumber">No Metadata Documentation available.</param>
        /// <param name="productCategoryId">No Metadata Documentation available.</param>
        public ObjectResult<ProductInfo> ProductInfo_GetByProductCategoryId_Child_Paging_Visible(global::System.String languageId, Nullable<global::System.Int32> pageSize, Nullable<global::System.Int32> pageNumber, Nullable<global::System.Guid> productCategoryId, MergeOption mergeOption)
        {
            ObjectParameter languageIdParameter;
            if (languageId != null)
            {
                languageIdParameter = new ObjectParameter("LanguageId", languageId);
            }
            else
            {
                languageIdParameter = new ObjectParameter("LanguageId", typeof(global::System.String));
            }
    
            ObjectParameter pageSizeParameter;
            if (pageSize.HasValue)
            {
                pageSizeParameter = new ObjectParameter("PageSize", pageSize);
            }
            else
            {
                pageSizeParameter = new ObjectParameter("PageSize", typeof(global::System.Int32));
            }
    
            ObjectParameter pageNumberParameter;
            if (pageNumber.HasValue)
            {
                pageNumberParameter = new ObjectParameter("PageNumber", pageNumber);
            }
            else
            {
                pageNumberParameter = new ObjectParameter("PageNumber", typeof(global::System.Int32));
            }
    
            ObjectParameter productCategoryIdParameter;
            if (productCategoryId.HasValue)
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", productCategoryId);
            }
            else
            {
                productCategoryIdParameter = new ObjectParameter("ProductCategoryId", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<ProductInfo>("ProductInfo_GetByProductCategoryId_Child_Paging_Visible", mergeOption, languageIdParameter, pageSizeParameter, pageNumberParameter, productCategoryIdParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="Cart")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cart : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cart object.
        /// </summary>
        /// <param name="cartId">Initial value of the CartId property.</param>
        public static Cart CreateCart(global::System.Int32 cartId)
        {
            Cart cart = new Cart();
            cart.CartId = cartId;
            return cart;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CartId
        {
            get
            {
                return _CartId;
            }
            set
            {
                if (_CartId != value)
                {
                    OnCartIdChanging(value);
                    ReportPropertyChanging("CartId");
                    _CartId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CartId");
                    OnCartIdChanged();
                }
            }
        }
        private global::System.Int32 _CartId;
        partial void OnCartIdChanging(global::System.Int32 value);
        partial void OnCartIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ListProducts
        {
            get
            {
                return _ListProducts;
            }
            set
            {
                OnListProductsChanging(value);
                ReportPropertyChanging("ListProducts");
                _ListProducts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ListProducts");
                OnListProductsChanged();
            }
        }
        private global::System.String _ListProducts;
        partial void OnListProductsChanging(global::System.String value);
        partial void OnListProductsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobilephone
        {
            get
            {
                return _Mobilephone;
            }
            set
            {
                OnMobilephoneChanging(value);
                ReportPropertyChanging("Mobilephone");
                _Mobilephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobilephone");
                OnMobilephoneChanged();
            }
        }
        private global::System.String _Mobilephone;
        partial void OnMobilephoneChanging(global::System.String value);
        partial void OnMobilephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        public static Customer CreateCustomer(global::System.Guid customerId)
        {
            Customer customer = new Customer();
            customer.CustomerId = customerId;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Guid _CustomerId;
        partial void OnCustomerIdChanging(global::System.Guid value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobilephone
        {
            get
            {
                return _Mobilephone;
            }
            set
            {
                OnMobilephoneChanging(value);
                ReportPropertyChanging("Mobilephone");
                _Mobilephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobilephone");
                OnMobilephoneChanged();
            }
        }
        private global::System.String _Mobilephone;
        partial void OnMobilephoneChanging(global::System.String value);
        partial void OnMobilephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TotalBuyPrice
        {
            get
            {
                return _TotalBuyPrice;
            }
            set
            {
                OnTotalBuyPriceChanging(value);
                ReportPropertyChanging("TotalBuyPrice");
                _TotalBuyPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalBuyPrice");
                OnTotalBuyPriceChanged();
            }
        }
        private Nullable<global::System.Int64> _TotalBuyPrice;
        partial void OnTotalBuyPriceChanging(Nullable<global::System.Int64> value);
        partial void OnTotalBuyPriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        public static Order CreateOrder(global::System.Guid orderId)
        {
            Order order = new Order();
            order.OrderId = orderId;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CustomerId;
        partial void OnCustomerIdChanging(Nullable<global::System.Guid> value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                OnTotalPriceChanging(value);
                ReportPropertyChanging("TotalPrice");
                _TotalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPrice");
                OnTotalPriceChanged();
            }
        }
        private Nullable<global::System.Int64> _TotalPrice;
        partial void OnTotalPriceChanging(Nullable<global::System.Int64> value);
        partial void OnTotalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                OnDiscountChanging(value);
                ReportPropertyChanging("Discount");
                _Discount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discount");
                OnDiscountChanged();
            }
        }
        private Nullable<global::System.Int64> _Discount;
        partial void OnDiscountChanging(Nullable<global::System.Int64> value);
        partial void OnDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FinalPrice
        {
            get
            {
                return _FinalPrice;
            }
            set
            {
                OnFinalPriceChanging(value);
                ReportPropertyChanging("FinalPrice");
                _FinalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalPrice");
                OnFinalPriceChanged();
            }
        }
        private Nullable<global::System.Int64> _FinalPrice;
        partial void OnFinalPriceChanging(Nullable<global::System.Int64> value);
        partial void OnFinalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="OrderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        public static OrderDetail CreateOrderDetail(global::System.Guid orderId, global::System.Guid productId)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.OrderId = orderId;
            orderDetail.ProductId = productId;
            return orderDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SellPrice
        {
            get
            {
                return _SellPrice;
            }
            set
            {
                OnSellPriceChanging(value);
                ReportPropertyChanging("SellPrice");
                _SellPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellPrice");
                OnSellPriceChanged();
            }
        }
        private Nullable<global::System.Int64> _SellPrice;
        partial void OnSellPriceChanging(Nullable<global::System.Int64> value);
        partial void OnSellPriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productId">Initial value of the ProductId property.</param>
        public static Product CreateProduct(global::System.Guid productId)
        {
            Product product = new Product();
            product.ProductId = productId;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ExistStatus
        {
            get
            {
                return _ExistStatus;
            }
            set
            {
                OnExistStatusChanging(value);
                ReportPropertyChanging("ExistStatus");
                _ExistStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExistStatus");
                OnExistStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _ExistStatus;
        partial void OnExistStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnExistStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ProductInfoId
        {
            get
            {
                return _ProductInfoId;
            }
            set
            {
                OnProductInfoIdChanging(value);
                ReportPropertyChanging("ProductInfoId");
                _ProductInfoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductInfoId");
                OnProductInfoIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ProductInfoId;
        partial void OnProductInfoIdChanging(Nullable<global::System.Guid> value);
        partial void OnProductInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="ProductCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductCategory object.
        /// </summary>
        /// <param name="productCategoryId">Initial value of the ProductCategoryId property.</param>
        /// <param name="languageId">Initial value of the LanguageId property.</param>
        public static ProductCategory CreateProductCategory(global::System.Guid productCategoryId, global::System.String languageId)
        {
            ProductCategory productCategory = new ProductCategory();
            productCategory.ProductCategoryId = productCategoryId;
            productCategory.LanguageId = languageId;
            return productCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductCategoryId
        {
            get
            {
                return _ProductCategoryId;
            }
            set
            {
                if (_ProductCategoryId != value)
                {
                    OnProductCategoryIdChanging(value);
                    ReportPropertyChanging("ProductCategoryId");
                    _ProductCategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductCategoryId");
                    OnProductCategoryIdChanged();
                }
            }
        }
        private global::System.Guid _ProductCategoryId;
        partial void OnProductCategoryIdChanging(global::System.Guid value);
        partial void OnProductCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                if (_LanguageId != value)
                {
                    OnLanguageIdChanging(value);
                    ReportPropertyChanging("LanguageId");
                    _LanguageId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LanguageId");
                    OnLanguageIdChanged();
                }
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParrentId
        {
            get
            {
                return _ParrentId;
            }
            set
            {
                OnParrentIdChanging(value);
                ReportPropertyChanging("ParrentId");
                _ParrentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParrentId");
                OnParrentIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ParrentId;
        partial void OnParrentIdChanging(Nullable<global::System.Guid> value);
        partial void OnParrentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="ProductImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductImage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductImage object.
        /// </summary>
        /// <param name="productImageID">Initial value of the ProductImageID property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="productInfoId">Initial value of the ProductInfoId property.</param>
        public static ProductImage CreateProductImage(global::System.Guid productImageID, global::System.String path, global::System.Guid productInfoId)
        {
            ProductImage productImage = new ProductImage();
            productImage.ProductImageID = productImageID;
            productImage.Path = path;
            productImage.ProductInfoId = productInfoId;
            return productImage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductImageID
        {
            get
            {
                return _ProductImageID;
            }
            set
            {
                if (_ProductImageID != value)
                {
                    OnProductImageIDChanging(value);
                    ReportPropertyChanging("ProductImageID");
                    _ProductImageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductImageID");
                    OnProductImageIDChanged();
                }
            }
        }
        private global::System.Guid _ProductImageID;
        partial void OnProductImageIDChanging(global::System.Guid value);
        partial void OnProductImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductInfoId
        {
            get
            {
                return _ProductInfoId;
            }
            set
            {
                OnProductInfoIdChanging(value);
                ReportPropertyChanging("ProductInfoId");
                _ProductInfoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductInfoId");
                OnProductInfoIdChanged();
            }
        }
        private global::System.Guid _ProductInfoId;
        partial void OnProductInfoIdChanging(global::System.Guid value);
        partial void OnProductInfoIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommerceModel", Name="ProductInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductInfo object.
        /// </summary>
        /// <param name="productInfoId">Initial value of the ProductInfoId property.</param>
        /// <param name="languageId">Initial value of the LanguageId property.</param>
        public static ProductInfo CreateProductInfo(global::System.Guid productInfoId, global::System.String languageId)
        {
            ProductInfo productInfo = new ProductInfo();
            productInfo.ProductInfoId = productInfoId;
            productInfo.LanguageId = languageId;
            return productInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductInfoId
        {
            get
            {
                return _ProductInfoId;
            }
            set
            {
                if (_ProductInfoId != value)
                {
                    OnProductInfoIdChanging(value);
                    ReportPropertyChanging("ProductInfoId");
                    _ProductInfoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductInfoId");
                    OnProductInfoIdChanged();
                }
            }
        }
        private global::System.Guid _ProductInfoId;
        partial void OnProductInfoIdChanging(global::System.Guid value);
        partial void OnProductInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ProductCategoryId
        {
            get
            {
                return _ProductCategoryId;
            }
            set
            {
                OnProductCategoryIdChanging(value);
                ReportPropertyChanging("ProductCategoryId");
                _ProductCategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductCategoryId");
                OnProductCategoryIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ProductCategoryId;
        partial void OnProductCategoryIdChanging(Nullable<global::System.Guid> value);
        partial void OnProductCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                if (_LanguageId != value)
                {
                    OnLanguageIdChanging(value);
                    ReportPropertyChanging("LanguageId");
                    _LanguageId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LanguageId");
                    OnLanguageIdChanged();
                }
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Int64> _Price;
        partial void OnPriceChanging(Nullable<global::System.Int64> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }

    #endregion
    
}
