//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LinkResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/AboutUs.aspx.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/Contact.aspx.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/Home.aspx.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en.
        /// </summary>
        internal static string LanguageLink {
            get {
                return ResourceManager.GetString("LanguageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Optic.
        /// </summary>
        internal static string PG01 {
            get {
                return ResourceManager.GetString("PG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Equipment.
        /// </summary>
        internal static string PG02 {
            get {
                return ResourceManager.GetString("PG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Device.
        /// </summary>
        internal static string PG03 {
            get {
                return ResourceManager.GetString("PG03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCTV.
        /// </summary>
        internal static string PG04 {
            get {
                return ResourceManager.GetString("PG04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Equipment.
        /// </summary>
        internal static string PG05 {
            get {
                return ResourceManager.GetString("PG05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-building.
        /// </summary>
        internal static string SL01 {
            get {
                return ResourceManager.GetString("SL01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATV.
        /// </summary>
        internal static string SL02 {
            get {
                return ResourceManager.GetString("SL02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless Network.
        /// </summary>
        internal static string SL03 {
            get {
                return ResourceManager.GetString("SL03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/Solutions/.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
    }
}
