//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TextResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Manager.
        /// </summary>
        internal static string ContentManager {
            get {
                return ResourceManager.GetString("ContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website contents: company introduction, vision, etc....
        /// </summary>
        internal static string ContentManagerHeaderSmall {
            get {
                return ResourceManager.GetString("ContentManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUser.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTaken.
        /// </summary>
        internal static string DateTaken {
            get {
                return ResourceManager.GetString("DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Album Manager.
        /// </summary>
        internal static string ImageAlbumManager {
            get {
                return ResourceManager.GetString("ImageAlbumManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s images.
        /// </summary>
        internal static string ImageAlbumManagerHeaderSmall {
            get {
                return ResourceManager.GetString("ImageAlbumManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Manager.
        /// </summary>
        internal static string ImageManager {
            get {
                return ResourceManager.GetString("ImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage images: banner, hero units, etc....
        /// </summary>
        internal static string ImageManagerHeaderSmall {
            get {
                return ResourceManager.GetString("ImageManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPublished.
        /// </summary>
        internal static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date.
        /// </summary>
        internal static string LastUpdateDate {
            get {
                return ResourceManager.GetString("LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update User.
        /// </summary>
        internal static string LastUpdateUser {
            get {
                return ResourceManager.GetString("LastUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Manager.
        /// </summary>
        internal static string NewsCategoryManager {
            get {
                return ResourceManager.GetString("NewsCategoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage News Categories.
        /// </summary>
        internal static string NewsCategoryManagerHeaderSmall {
            get {
                return ResourceManager.GetString("NewsCategoryManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCategoryManager.
        /// </summary>
        internal static string ProductCategoryManager {
            get {
                return ResourceManager.GetString("ProductCategoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product Categories.
        /// </summary>
        internal static string ProductCategoryManagerHeaderSmall {
            get {
                return ResourceManager.GetString("ProductCategoryManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Info Manager.
        /// </summary>
        internal static string ProductInfoManager {
            get {
                return ResourceManager.GetString("ProductInfoManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product Info.
        /// </summary>
        internal static string ProductInfoManagerHeaderSmall {
            get {
                return ResourceManager.GetString("ProductInfoManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss Provider Manager.
        /// </summary>
        internal static string RssProviderManager {
            get {
                return ResourceManager.GetString("RssProviderManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rss Provider.
        /// </summary>
        internal static string RssProviderManagerHeaderSmall {
            get {
                return ResourceManager.GetString("RssProviderManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss Source Manager.
        /// </summary>
        internal static string RssSourceManager {
            get {
                return ResourceManager.GetString("RssSourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rss Source.
        /// </summary>
        internal static string RssSourceManagerHeaderSmall {
            get {
                return ResourceManager.GetString("RssSourceManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Image Manager.
        /// </summary>
        internal static string SpecialImageManager {
            get {
                return ResourceManager.GetString("SpecialImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s special images.
        /// </summary>
        internal static string SpecialImageManagerHeaderSmall {
            get {
                return ResourceManager.GetString("SpecialImageManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Image Type Manager.
        /// </summary>
        internal static string SpecialImageTypeManager {
            get {
                return ResourceManager.GetString("SpecialImageTypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s special image types.
        /// </summary>
        internal static string SpecialImageTypeManagerHeaderSmall {
            get {
                return ResourceManager.GetString("SpecialImageTypeManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Content Manager.
        /// </summary>
        internal static string StaticContentManager {
            get {
                return ResourceManager.GetString("StaticContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage webiste&apos;s static content.
        /// </summary>
        internal static string StaticContentManagerHeaderSmall {
            get {
                return ResourceManager.GetString("StaticContentManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Content Type Manager.
        /// </summary>
        internal static string StaticContentTypeManager {
            get {
                return ResourceManager.GetString("StaticContentTypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s static content type.
        /// </summary>
        internal static string StaticContentTypeManagerHeaderSmall {
            get {
                return ResourceManager.GetString("StaticContentTypeManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Manager.
        /// </summary>
        internal static string StatusManager {
            get {
                return ResourceManager.GetString("StatusManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage news&apos; status.
        /// </summary>
        internal static string StatusManagerHeaderSmall {
            get {
                return ResourceManager.GetString("StatusManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Manager.
        /// </summary>
        internal static string SupportManager {
            get {
                return ResourceManager.GetString("SupportManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s support.
        /// </summary>
        internal static string SupportManagerHeaderSmall {
            get {
                return ResourceManager.GetString("SupportManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Type Manager.
        /// </summary>
        internal static string SupportTypeManager {
            get {
                return ResourceManager.GetString("SupportTypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s support type.
        /// </summary>
        internal static string SupportTypeManagerHeaderSmall {
            get {
                return ResourceManager.GetString("SupportTypeManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manager.
        /// </summary>
        internal static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage website&apos;s users.
        /// </summary>
        internal static string UserManagerHeaderSmall {
            get {
                return ResourceManager.GetString("UserManagerHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
    }
}
