//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Artnman.Bulletin.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NewsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NewsEntities object using the connection string found in the 'NewsEntities' section of the application configuration file.
        /// </summary>
        public NewsEntities() : base("name=NewsEntities", "NewsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewsEntities object.
        /// </summary>
        public NewsEntities(string connectionString) : base(connectionString, "NewsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewsEntities object.
        /// </summary>
        public NewsEntities(EntityConnection connection) : base(connection, "NewsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<News> News
        {
            get
            {
                if ((_News == null))
                {
                    _News = base.CreateObjectSet<News>("News");
                }
                return _News;
            }
        }
        private ObjectSet<News> _News;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewsCategory> NewsCategory
        {
            get
            {
                if ((_NewsCategory == null))
                {
                    _NewsCategory = base.CreateObjectSet<NewsCategory>("NewsCategory");
                }
                return _NewsCategory;
            }
        }
        private ObjectSet<NewsCategory> _NewsCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewsComment> NewsComment
        {
            get
            {
                if ((_NewsComment == null))
                {
                    _NewsComment = base.CreateObjectSet<NewsComment>("NewsComment");
                }
                return _NewsComment;
            }
        }
        private ObjectSet<NewsComment> _NewsComment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewsStatus> NewsStatus
        {
            get
            {
                if ((_NewsStatus == null))
                {
                    _NewsStatus = base.CreateObjectSet<NewsStatus>("NewsStatus");
                }
                return _NewsStatus;
            }
        }
        private ObjectSet<NewsStatus> _NewsStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RssProvider> RssProvider
        {
            get
            {
                if ((_RssProvider == null))
                {
                    _RssProvider = base.CreateObjectSet<RssProvider>("RssProvider");
                }
                return _RssProvider;
            }
        }
        private ObjectSet<RssProvider> _RssProvider;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RssSource> RssSource
        {
            get
            {
                if ((_RssSource == null))
                {
                    _RssSource = base.CreateObjectSet<RssSource>("RssSource");
                }
                return _RssSource;
            }
        }
        private ObjectSet<RssSource> _RssSource;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the News EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNews(News news)
        {
            base.AddObject("News", news);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewsCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewsCategory(NewsCategory newsCategory)
        {
            base.AddObject("NewsCategory", newsCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewsComment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewsComment(NewsComment newsComment)
        {
            base.AddObject("NewsComment", newsComment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewsStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewsStatus(NewsStatus newsStatus)
        {
            base.AddObject("NewsStatus", newsStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RssProvider EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRssProvider(RssProvider rssProvider)
        {
            base.AddObject("RssProvider", rssProvider);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RssSource EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRssSource(RssSource rssSource)
        {
            base.AddObject("RssSource", rssSource);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NewsModel", Name="News")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class News : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new News object.
        /// </summary>
        /// <param name="newsId">Initial value of the NewsId property.</param>
        public static News CreateNews(global::System.Guid newsId)
        {
            News news = new News();
            news.NewsId = newsId;
            return news;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NewsId
        {
            get
            {
                return _NewsId;
            }
            set
            {
                if (_NewsId != value)
                {
                    OnNewsIdChanging(value);
                    ReportPropertyChanging("NewsId");
                    _NewsId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NewsId");
                    OnNewsIdChanged();
                }
            }
        }
        private global::System.Guid _NewsId;
        partial void OnNewsIdChanging(global::System.Guid value);
        partial void OnNewsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NewsCategoryId
        {
            get
            {
                return _NewsCategoryId;
            }
            set
            {
                OnNewsCategoryIdChanging(value);
                ReportPropertyChanging("NewsCategoryId");
                _NewsCategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsCategoryId");
                OnNewsCategoryIdChanged();
            }
        }
        private Nullable<global::System.Guid> _NewsCategoryId;
        partial void OnNewsCategoryIdChanging(Nullable<global::System.Guid> value);
        partial void OnNewsCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NewsStatusId
        {
            get
            {
                return _NewsStatusId;
            }
            set
            {
                OnNewsStatusIdChanging(value);
                ReportPropertyChanging("NewsStatusId");
                _NewsStatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsStatusId");
                OnNewsStatusIdChanged();
            }
        }
        private Nullable<global::System.Guid> _NewsStatusId;
        partial void OnNewsStatusIdChanging(Nullable<global::System.Guid> value);
        partial void OnNewsStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subtitle
        {
            get
            {
                return _Subtitle;
            }
            set
            {
                OnSubtitleChanging(value);
                ReportPropertyChanging("Subtitle");
                _Subtitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subtitle");
                OnSubtitleChanged();
            }
        }
        private global::System.String _Subtitle;
        partial void OnSubtitleChanging(global::System.String value);
        partial void OnSubtitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exerpt
        {
            get
            {
                return _Exerpt;
            }
            set
            {
                OnExerptChanging(value);
                ReportPropertyChanging("Exerpt");
                _Exerpt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exerpt");
                OnExerptChanged();
            }
        }
        private global::System.String _Exerpt;
        partial void OnExerptChanging(global::System.String value);
        partial void OnExerptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalViews
        {
            get
            {
                return _TotalViews;
            }
            set
            {
                OnTotalViewsChanging(value);
                ReportPropertyChanging("TotalViews");
                _TotalViews = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalViews");
                OnTotalViewsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalViews;
        partial void OnTotalViewsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalViewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalRates
        {
            get
            {
                return _TotalRates;
            }
            set
            {
                OnTotalRatesChanging(value);
                ReportPropertyChanging("TotalRates");
                _TotalRates = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRates");
                OnTotalRatesChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalRates;
        partial void OnTotalRatesChanging(Nullable<global::System.Int32> value);
        partial void OnTotalRatesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NewsModel", Name="NewsCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewsCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewsCategory object.
        /// </summary>
        /// <param name="newsCategoryId">Initial value of the NewsCategoryId property.</param>
        public static NewsCategory CreateNewsCategory(global::System.Guid newsCategoryId)
        {
            NewsCategory newsCategory = new NewsCategory();
            newsCategory.NewsCategoryId = newsCategoryId;
            return newsCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NewsCategoryId
        {
            get
            {
                return _NewsCategoryId;
            }
            set
            {
                if (_NewsCategoryId != value)
                {
                    OnNewsCategoryIdChanging(value);
                    ReportPropertyChanging("NewsCategoryId");
                    _NewsCategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NewsCategoryId");
                    OnNewsCategoryIdChanged();
                }
            }
        }
        private global::System.Guid _NewsCategoryId;
        partial void OnNewsCategoryIdChanging(global::System.Guid value);
        partial void OnNewsCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParrentId
        {
            get
            {
                return _ParrentId;
            }
            set
            {
                OnParrentIdChanging(value);
                ReportPropertyChanging("ParrentId");
                _ParrentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParrentId");
                OnParrentIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ParrentId;
        partial void OnParrentIdChanging(Nullable<global::System.Guid> value);
        partial void OnParrentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NewsModel", Name="NewsComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewsComment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewsComment object.
        /// </summary>
        /// <param name="newsCommentId">Initial value of the NewsCommentId property.</param>
        public static NewsComment CreateNewsComment(global::System.Guid newsCommentId)
        {
            NewsComment newsComment = new NewsComment();
            newsComment.NewsCommentId = newsCommentId;
            return newsComment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NewsCommentId
        {
            get
            {
                return _NewsCommentId;
            }
            set
            {
                if (_NewsCommentId != value)
                {
                    OnNewsCommentIdChanging(value);
                    ReportPropertyChanging("NewsCommentId");
                    _NewsCommentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NewsCommentId");
                    OnNewsCommentIdChanged();
                }
            }
        }
        private global::System.Guid _NewsCommentId;
        partial void OnNewsCommentIdChanging(global::System.Guid value);
        partial void OnNewsCommentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NewsId
        {
            get
            {
                return _NewsId;
            }
            set
            {
                OnNewsIdChanging(value);
                ReportPropertyChanging("NewsId");
                _NewsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsId");
                OnNewsIdChanged();
            }
        }
        private Nullable<global::System.Guid> _NewsId;
        partial void OnNewsIdChanging(Nullable<global::System.Guid> value);
        partial void OnNewsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fullname
        {
            get
            {
                return _Fullname;
            }
            set
            {
                OnFullnameChanging(value);
                ReportPropertyChanging("Fullname");
                _Fullname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fullname");
                OnFullnameChanged();
            }
        }
        private global::System.String _Fullname;
        partial void OnFullnameChanging(global::System.String value);
        partial void OnFullnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NewsModel", Name="NewsStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewsStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewsStatus object.
        /// </summary>
        /// <param name="newsStatusId">Initial value of the NewsStatusId property.</param>
        public static NewsStatus CreateNewsStatus(global::System.Guid newsStatusId)
        {
            NewsStatus newsStatus = new NewsStatus();
            newsStatus.NewsStatusId = newsStatusId;
            return newsStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NewsStatusId
        {
            get
            {
                return _NewsStatusId;
            }
            set
            {
                if (_NewsStatusId != value)
                {
                    OnNewsStatusIdChanging(value);
                    ReportPropertyChanging("NewsStatusId");
                    _NewsStatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NewsStatusId");
                    OnNewsStatusIdChanged();
                }
            }
        }
        private global::System.Guid _NewsStatusId;
        partial void OnNewsStatusIdChanging(global::System.Guid value);
        partial void OnNewsStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsPublished
        {
            get
            {
                return _IsPublished;
            }
            set
            {
                OnIsPublishedChanging(value);
                ReportPropertyChanging("IsPublished");
                _IsPublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublished");
                OnIsPublishedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsPublished;
        partial void OnIsPublishedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NewsModel", Name="RssProvider")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RssProvider : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RssProvider object.
        /// </summary>
        /// <param name="rssProviderId">Initial value of the RssProviderId property.</param>
        public static RssProvider CreateRssProvider(global::System.Guid rssProviderId)
        {
            RssProvider rssProvider = new RssProvider();
            rssProvider.RssProviderId = rssProviderId;
            return rssProvider;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RssProviderId
        {
            get
            {
                return _RssProviderId;
            }
            set
            {
                if (_RssProviderId != value)
                {
                    OnRssProviderIdChanging(value);
                    ReportPropertyChanging("RssProviderId");
                    _RssProviderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RssProviderId");
                    OnRssProviderIdChanged();
                }
            }
        }
        private global::System.Guid _RssProviderId;
        partial void OnRssProviderIdChanging(global::System.Guid value);
        partial void OnRssProviderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NewsModel", Name="RssSource")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RssSource : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RssSource object.
        /// </summary>
        /// <param name="rssSourceId">Initial value of the RssSourceId property.</param>
        public static RssSource CreateRssSource(global::System.Guid rssSourceId)
        {
            RssSource rssSource = new RssSource();
            rssSource.RssSourceId = rssSourceId;
            return rssSource;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RssSourceId
        {
            get
            {
                return _RssSourceId;
            }
            set
            {
                if (_RssSourceId != value)
                {
                    OnRssSourceIdChanging(value);
                    ReportPropertyChanging("RssSourceId");
                    _RssSourceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RssSourceId");
                    OnRssSourceIdChanged();
                }
            }
        }
        private global::System.Guid _RssSourceId;
        partial void OnRssSourceIdChanging(global::System.Guid value);
        partial void OnRssSourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.String _LanguageId;
        partial void OnLanguageIdChanging(global::System.String value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NewsCategoryId
        {
            get
            {
                return _NewsCategoryId;
            }
            set
            {
                OnNewsCategoryIdChanging(value);
                ReportPropertyChanging("NewsCategoryId");
                _NewsCategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsCategoryId");
                OnNewsCategoryIdChanged();
            }
        }
        private Nullable<global::System.Guid> _NewsCategoryId;
        partial void OnNewsCategoryIdChanging(Nullable<global::System.Guid> value);
        partial void OnNewsCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> RssProviderId
        {
            get
            {
                return _RssProviderId;
            }
            set
            {
                OnRssProviderIdChanging(value);
                ReportPropertyChanging("RssProviderId");
                _RssProviderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RssProviderId");
                OnRssProviderIdChanged();
            }
        }
        private Nullable<global::System.Guid> _RssProviderId;
        partial void OnRssProviderIdChanging(Nullable<global::System.Guid> value);
        partial void OnRssProviderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceLink
        {
            get
            {
                return _SourceLink;
            }
            set
            {
                OnSourceLinkChanging(value);
                ReportPropertyChanging("SourceLink");
                _SourceLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceLink");
                OnSourceLinkChanged();
            }
        }
        private global::System.String _SourceLink;
        partial void OnSourceLinkChanging(global::System.String value);
        partial void OnSourceLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _CreateUser;
        partial void OnCreateUserChanging(Nullable<global::System.Guid> value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private Nullable<global::System.Guid> _LastUpdateUser;
        partial void OnLastUpdateUserChanging(Nullable<global::System.Guid> value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();

        #endregion
    
    }

    #endregion
    
}
